name: 'Continuous Integration'

on:
  create:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'

jobs:
  run:
    uses: "nucleos/actions/.github/workflows/continuous-integration.yml@main"
    with:
      PHP_EXTENSIONS: ""
      PHP_VERSIONS: '8.3,8.4'
      SYMFONY_VERSIONS: "7.4,8.0"
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
